import { z } from "zod";

export const forumData = [
  { id: "4", name: "综合版1" },
  { id: "98", name: "DANGER_U" },
  { id: "20", name: "欢乐恶搞" },
  { id: "121", name: "速报2" },
  { id: "17", name: "绘画" },
  { id: "110", name: "社畜" },
  { id: "19", name: "故事" },
  { id: "81", name: "都市怪谈" },
  { id: "37", name: "军武" },
  { id: "30", name: "技术宅" },
  { id: "75", name: "数码" },
  { id: "118", name: "宠物" },
  { id: "97", name: "女装2" },
  { id: "106", name: "买买买" },
  { id: "14", name: "动画综合" },
  { id: "12", name: "漫画" },
  { id: "53", name: "婆罗门一" },
  { id: "31", name: "影视" },
  { id: "116", name: "主播管人" },
  { id: "45", name: "卡牌桌游" },
  { id: "9", name: "特摄" },
  { id: "102", name: "战锤" },
  { id: "39", name: "胶佬" },
  { id: "94", name: "铁道厨" },
  { id: "6", name: "VOCALOID" },
  { id: "90", name: "小马" },
  { id: "5", name: "东方Project" },
  { id: "93", name: "舰娘" },
  { id: "111", name: "跑团" },
  { id: "57", name: "创作茶水间" },
  { id: "91", name: "规则怪谈" },
  { id: "11", name: "海龟汤" },
  { id: "15", name: "科学" },
  { id: "103", name: "文学" },
  { id: "35", name: "音乐" },
  { id: "27", name: "AI" },
  { id: "115", name: "摄影" },
  { id: "112", name: "ROLL点" },
  { id: "2", name: "游戏综合" },
  { id: "3", name: "手游专楼" },
  { id: "25", name: "任天堂" },
  { id: "22", name: "腾讯游戏" },
  { id: "23", name: "暴雪游戏" },
  { id: "124", name: "SE" },
  { id: "70", name: "V社" },
  { id: "28", name: "怪物猎人" },
  { id: "68", name: "鹰角游戏" },
  { id: "47", name: "米哈游" },
  { id: "34", name: "音游打卡" },
  { id: "10", name: "联机" },
  { id: "62", name: "露营" },
  { id: "113", name: "育儿" },
  { id: "120", name: "自救互助" },
  { id: "32", name: "料理" },
  { id: "33", name: "体育" },
  { id: "56", name: "学业打卡" },
  { id: "89", name: "日记" },
  { id: "18", name: "值班室" },
  { id: "117", name: "技术支持" },
  { id: "96", name: "版务" },
  { id: "60", name: "百脑汇" },
];

export const forumIds = forumData.map((f) => f.id);

const forumIdLiterals = forumIds.map((id) => z.literal(id)) as [
  z.ZodLiteral<string>,
  z.ZodLiteral<string>,
  ...z.ZodLiteral<string>[],
];

export const fidSchema = z.union(forumIdLiterals).describe("版块ID"); 